name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "2.15.0"
description = "A big progressive questing modpack for Minecraft 1.7.10 balanced around the NTM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fe74819ad3ab16b7ef8bbb7d9dcbde4541443feb361275d1e06a5dedd9b65dd"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
