name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "2.15.0"
description = "A big progressive questing modpack for Minecraft 1.7.10 balanced around the NTM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d96fe227402a0a17520ca305ddfa6c7372ee8069b7386c9eb03df374f00b0203"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
