name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "2.15.0"
description = "A big progressive questing modpack for Minecraft 1.7.10 balanced around the NTM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71357e74541e1d6f00a8e994ee031d3782b114f316249336c9e24669ef8611c9"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
