#Configuration file for early hodgepodge class transformers
#Fri Oct 09 22:05:20 MDT 2026
noLeanerForgeConfiguration=false
noFasterForgeEventTransformer=false
noAsyncFmlFileLog=false
noNukeBaseMod=false
noFmlRelaunchLogLoggerCache=false
