#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Fri Oct 09 22:05:27 MDT 2026
enableDebugOptions=false
disableUpdateMessage=true
saveCompiledShaders=false
enableShaders=false
maxShadowRenderDistance=12
allowUnknownShaders=false
shaderPack=BountifulStarsALPHA0.0.3.zip
